package com.beverly.hills.money.gang.entities.enemies;

public enum EnemyTextureRegistry {
    IDLETEXFRONTREG,
    MOVING1TEXFRONTREG,
    MOVING2TEXFRONTREG,
    MOVING3TEXFRONTREG,
    IDLETEXBACKREG,
    MOVING1TEXBACKREG,
    MOVING2TEXBACKREG,
    MOVING3TEXBACKREG,
    IDLETEXLEFTREG,
    MOVING1TEXLEFTREG,
    MOVING2TEXLEFTREG,
    MOVING3TEXLEFTREG,
    IDLETEXRIGHTREG,
    MOVING1TEXRIGHTREG,
    MOVING2TEXRIGHTREG,
    MOVING3TEXRIGHTREG,
    SHOOTINGTEXRIGHTREG,
    SHOOTINGTEXBACKTREG,
    SHOOTINGTEXLEFTREG,
    SHOOTINGTEXFRONTREG,
    DEATHTEXREG
}